server:
  port: 8083

app:
  deviceServiceUrl: ${DEVICE_SERVICE_URL:http://localhost:8082}
  influx:
    url: ${INFLUX_URL:http://localhost:8086}
    token: ${INFLUX_TOKEN:supersecrettoken}
    org: ${INFLUX_ORG:platform}
    bucket: ${INFLUX_BUCKET:telemetry}
  kafka:
    bootstrap: ${KAFKA_BOOTSTRAP:localhost:9092}
  ingestion:
    maxQueue: 5000
    workerThreads: 8

spring:
  kafka:
    bootstrap-servers: ${app.kafka.bootstrap}
    producer:
      acks: all
      retries: 5
      properties:
        linger.ms: 5
        batch.size: 32768
        delivery.timeout.ms: 120000

springdoc:
  api-docs:
    path: /v3/api-docs
